main: com.sereneoasis.SereneNPCs
name: SereneNPCs
author: Sujan
version: 1.0.0
api-version: '1.20'
load: STARTUP
loadbefore: [SereneWorldGen]
commands:
  serenenpcs:
    description: Your description
    usage: /<command>